# Generated by Django 3.2.5 on 2021-07-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.CharField(default='Description', max_length=1000, null=True),
        ),
    ]
